# fly.toml app configuration file generated for bitter-morning-162 on 2023-10-22T21:59:23-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bitter-morning-162"
primary_region = "iad"

[build]

[env]
  PORT = 3000

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
